### 【問題1】SimpleRNNのフォワードプロパゲーション実装

参考: https://github.com/oreilly-japan/deep-learning-from-scratch-2

In [2]:
import numpy as np

class SimpleRNN:

    def __init__(self, Wx, Wh, b):
        self.Wx = Wx
        self.Wh = Wh
        self.b = b

    def forward(self, x, h_prev):
        t = h_prev @ self.Wh + x @ self.Wx + b
        return np.tanh(t)


### 【問題2】小さな配列でのフォワードプロパゲーションの実験

In [4]:
x = np.array([[[1, 2], [2, 3], [3, 4]]])/100 # (batch_size, n_sequences, n_features)
w_x = np.array([[1, 3, 5, 7], [3, 5, 7, 8]])/100 # (n_features, n_nodes)
w_h = np.array([[1, 3, 5, 7], [2, 4, 6, 8], [3, 5, 7, 8], [4, 6, 8, 10]])/100 # (n_nodes, n_nodes)
batch_size = x.shape[0] # 1
n_sequences = x.shape[1] # 3
n_features = x.shape[2] # 2
n_nodes = w_x.shape[1] # 4
h = np.zeros((batch_size, n_nodes)) # (batch_size, n_nodes)
b = np.array([1, 1, 1, 1]) # (n_nodes,)

print(x)
hoge = SimpleRNN(w_x, w_h, b)
print(hoge.forward(x, h))

[[[0.01 0.02]
  [0.02 0.03]
  [0.03 0.04]]]
[[[0.76188798 0.76213958 0.76239095 0.76255841]
  [0.76205574 0.76247469 0.76289301 0.76318545]
  [0.7622234  0.76280939 0.76339414 0.76381105]]]
