### 【問題1】行列積を手計算する
```
AとBの行列積を手計算で解いてください。

計算過程もマークダウンテキストを用いて説明してください。
```

AとBの定義
```
a = np.array([
    [-1, 2, 3], 
    [4, -5, 6],
    [7, 8, -9]])
b = np.array([
    [0, 2, 1],
    [0, 2, -8],
    [2, 9, -1]])
```

aの行、bの列の対応する値をかけて、その合計値を1つの値とする
```
[
    [ (0+0+6), (-2+4+27), (-1-16-3) ]
    [ (0+0+12), (8-10+54), (4+40-6) ]
    [ (0+0-18), (14+16-81), (7-64+9) ]
]
```
計算すると
```
[
    [ 6, 29, -20 ]
    [ 12, 52, 38 ]
    [ -18, -51, -48 ]
]
```

### 【問題2】NumPyの関数による計算
```
この行列積はNumPyのnp.matmul()やnp.dot()、または@演算子を使うことで簡単に計算できます。
```

In [35]:
import numpy as np
a = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

print(np.matmul(a, b))
print(np.dot(a, b))
print(a@ b)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


### 【問題3】ある要素の計算を実装

In [28]:
sum([a[0][i] * b[i][0] for i in range(3)])

6

### 【問題4】行列積を行う関数の作成

In [45]:
def _calc(a_i, b_i):
    return sum([a[a_i][idx] * b[idx][b_i] for idx in range(3)])

def calc(a_list, b_list):
    result = []
    for a_i in range(len(a_list)):
        tmp = []
        for b_i in range(len(b_list[0])):
            tmp.append(_calc(a_i, b_i))
        result.append(tmp)
    return result

print(calc(a, b))

[[6, 29, -20], [12, 52, 38], [-18, -51, -48]]


### 【問題5】計算が定義されない入力を判定する
```
問題4で作成した関数は、実装方法によってはこのDとEの配列を入力しても動いてしまう可能性があります。
この場合、不適切な計算が行われることになります。また、途中でエラーになる場合でも、
なぜエラーになったかが直接的には分かりづらいメッセージが表示されます。
if文などによってこれを防ぎ、入力される形に問題があることをprint()を使い表示するコードを書き加えてください。
```

In [54]:
def calc2(a_list, b_list):
    if len(a_list[0]) != len(b_list):
        raise Exception("calc2: Invalid arguments.")
    result = []
    for a_i in range(len(a_list)):
        tmp = []
        for b_i in range(len(b_list[0])):
            tmp.append(_calc(a_i, b_i))
        result.append(tmp)
    return result

c = np.array([[1, 2, 3]])  # invalid arg
calc2(a, c) # error

Exception: calc2: Invalid arguments.

### 【問題6】転置
```
片方の行列を転置することで、行列積が計算できるようになります。
np.transpose()や.Tアトリビュートを用いて転置し、行列積を計算してください。
```

In [55]:
calc2(a, c.T)

[[6], [12], [-18]]